### ISSUE TITLE
v1.3 tweaks

### ISSUE THREAD

**Issue by Noah2610** [Noah2610/LD45-WorkingTitle#42]
Final v1.3 settings and UI tweaks. Post comments for anything you think of.

**Comment by dimling** [comment]
Increase text size of "Paused", "Level Clear!" and "Working Title" times 3-4

**Comment by dimling** [comment]
- increase text size of "Paused", "Level Clear!" and "Working title" by 200%-400%
- change "Working Title" to all caps

**Comment by Noah2610** [comment]
Figure out which levels are initially locked, and through which levels they are unlocked.
